#!/bin/bash

# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-HepPh.txtD.txt --output=/user/btech/arpitk/GraphData/output/CollNet/HepPh >HepPhOut.txt 2>HepPhLog.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-GrQc.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output/CollNet/GrQc3 >Out/GrQcOut.txt 2>Log/GrQcLog.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-HepTh.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output/CollNet/HepTh3 >Out/HepThOut.txt 2>Log/HepThLog.txt

spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/RoadNet/roadNet-CA.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output/RoadNet/roadNet-CA3 >Out/roadnetCAOut.txt 2>Log/roadnetCALog.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/RoadNet/roadNet-PA.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output/RoadNet/roadNet-PA3 >Out/roadnetPAOut.txt 2>Log/roadnetPALog.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/RoadNet/roadNet-TX.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output/RoadNet/roadNet-TX3 >Out/roadnetTXOut.txt 2>Log/roadnetTXLog.txt


spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-CondMat.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output/CollNet/CondMat3 >Out/CondMatOut.txt 2>Log/CondMatLog.txt