#!/bin/bash

# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-GrQc.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/CollNet/GrQc1DE >Out/GrQcOut_1DE.txt 2>Log/GrQcLog_1DE.txt
# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-HepTh.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/CollNet/HepTh1DE >Out/HepThOut_1DE.txt 2>Log/HepThLog_1DE.txt

# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/RoadNet/roadNet-CA.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/RoadNet/roadNet-CA1DE2 >Out/roadnetCAOut_1DE.txt 2>Log/roadnetCALog_1DE.txt
# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/RoadNet/roadNet-PA.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/RoadNet/roadNet-PA1DE2 >Out/roadnetPAOut_1DE.txt 2>Log/roadnetPALog_1DE.txt
# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/RoadNet/roadNet-TX.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/RoadNet/roadNet-TX1DE2 >Out/roadnetTXOut_1DE.txt 2>Log/roadnetTXLog_1DE.txt

# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/SocialNet/facebook_combined.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/SocialNet/FB1DE2 >Out/FBOut_1DE.txt 2>Log/FBLog_1DE.txt


# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/NGTC/com-amazon.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/NGTC/Amazon1DE2 >Out/AmazonOut_1DE.txt 2>Log/AmazonLog_1DE.txt



# # spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/CollNet/CA-HepPh.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/CollNet/HepPh1DE >Out/HepPhOut_1DE.txt 2>Log/HepPhLog_1DE.txt


# spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 15 --executor-cores 8 sparkwordcount-0.0.1-SNAPSHOT.jar dominatingset /user/btech/arpitk/GraphData/NGTC/com-youtube.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/GraphData/output1/NGTC/Youtube1DE >Out/youtubeOut_1DE.txt 2>Log/youtubeLog_1DE.txt


spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-GrQc.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/GrQc-noPart1 >out/GrQc-noPart1.txt 2>log/GrQc-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-HepTh.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/HepTh-noPart1 >out/HepTh-noPart1.txt 2>log/HepTh-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-CA.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/roadNetCA-noPart1 >out/roadNetCA-noPart1.txt 2>log/roadNetCA-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-PA.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/roadNetPA-noPart1 >out/roadNetPA-noPart1.txt 2>log/roadNetPA-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-TX.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/roadNetTX-noPart1 >out/roadNetTX-noPart1.txt 2>log/roadNetTX-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/com-amazon.ungraph.txtD.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/amazon-noPart1 >out/amazon-noPart1.txt 2>log/amazon-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/facebook_combined.txtD.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/fb-noPart1 >out/fb-noPart1.txt 2>log/fb-noPart1.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/com-youtube.ungraph.txtD.txt --numEPart=1 --output=/user/btech/arpitk/NewGraph/output1/youtube-noPart1 >out/youtube-noPart1.txt 2>log/youtube-noPart1.txt

spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-GrQc.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/GrQc-noPart20 >out/GrQc-noPart20.txt 2>log/GrQc-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-HepTh.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/HepTh-noPart20 >out/HepTh-noPart20.txt 2>log/HepTh-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-CA.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetCA-noPart20 >out/roadNetCA-noPart20.txt 2>log/roadNetCA-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-PA.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetPA-noPart20 >out/roadNetPA-noPart20.txt 2>log/roadNetPA-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-TX.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetTX-noPart20 >out/roadNetTX-noPart20.txt 2>log/roadNetTX-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/com-amazon.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/amazon-noPart20 >out/amazon-noPart20.txt 2>log/amazon-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/facebook_combined.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/fb-noPart20 >out/fb-noPart20.txt 2>log/fb-noPart20.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_un.jar dominatingset /user/btech/arpitk/NewGraph/input/com-youtube.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/youtube-noPart20 >out/youtube-noPart20.txt 2>log/youtube-noPart20.txt


spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-GrQc.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/GrQc-Part1D >out/GrQc-Part1D.txt 2>log/GrQc-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-HepTh.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/HepTh-Part1D >out/HepTh-Part1D.txt 2>log/HepTh-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-CA.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetCA-Part1D >out/roadNetCA-Part1D.txt 2>log/roadNetCA-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-PA.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetPA-Part1D >out/roadNetPA-Part1D.txt 2>log/roadNetPA-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-TX.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetTX-Part1D >out/roadNetTX-Part1D.txt 2>log/roadNetTX-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/com-amazon.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/amazon-Part1D >out/amazon-Part1D.txt 2>log/amazon-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/facebook_combined.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/fb-Part1D >out/fb-Part1D.txt 2>log/fb-Part1D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_1d.jar dominatingset /user/btech/arpitk/NewGraph/input/com-youtube.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/youtube-Part1D >out/youtube-Part1D.txt 2>log/youtube-Part1D.txt


spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-GrQc.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/GrQc-Part2D >out/GrQc-Part2D.txt 2>log/GrQc-Part2D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/CA-HepTh.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/HepTh-Part2D >out/HepTh-Part2D.txt 2>log/HepTh-Part2D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-CA.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetCA-Part2D >out/roadNetCA-Part2D.txt 2>log/roadNetCA-Part2D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-PA.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetPA-Part2D >out/roadNetPA-Part2D.txt 2>log/roadNetPA-Part2D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/roadNet-TX.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/roadNetTX-Part2D >out/roadNetTX-Part2D.txt 2>log/roadNetTX-Part2D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/com-amazon.ungraph.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/amazon-Part2D >out/amazon-Part2D.txt 2>log/amazon-Part2D.txt
spark-submit --class com.cloudera.sparkwordcount.GraphReaderPageRank --master yarn-client --executor-memory 50G --num-executors 5 --executor-cores 8 DS_2d.jar dominatingset /user/btech/arpitk/NewGraph/input/facebook_combined.txtD.txt --numEPart=20 --output=/user/btech/arpitk/NewGraph/output1/fb-Part2D >out/fb-Part2D.txt 2>log/fb-Part2D.txt
